/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/add-birthday`; params?: Router.UnknownInputParams; } | { pathname: `/add-journal`; params?: Router.UnknownInputParams; } | { pathname: `/add-task`; params?: Router.UnknownInputParams; } | { pathname: `/avatar`; params?: Router.UnknownInputParams; } | { pathname: `/birthday-detail`; params?: Router.UnknownInputParams; } | { pathname: `/chat-history`; params?: Router.UnknownInputParams; } | { pathname: `/chat`; params?: Router.UnknownInputParams; } | { pathname: `/docs`; params?: Router.UnknownInputParams; } | { pathname: `/emotion`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/journal`; params?: Router.UnknownInputParams; } | { pathname: `/tasks`; params?: Router.UnknownInputParams; } | { pathname: `/vault`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/contexts/VaultContext`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/add-birthday`; params?: Router.UnknownOutputParams; } | { pathname: `/add-journal`; params?: Router.UnknownOutputParams; } | { pathname: `/add-task`; params?: Router.UnknownOutputParams; } | { pathname: `/avatar`; params?: Router.UnknownOutputParams; } | { pathname: `/birthday-detail`; params?: Router.UnknownOutputParams; } | { pathname: `/chat-history`; params?: Router.UnknownOutputParams; } | { pathname: `/chat`; params?: Router.UnknownOutputParams; } | { pathname: `/docs`; params?: Router.UnknownOutputParams; } | { pathname: `/emotion`; params?: Router.UnknownOutputParams; } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/journal`; params?: Router.UnknownOutputParams; } | { pathname: `/tasks`; params?: Router.UnknownOutputParams; } | { pathname: `/vault`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/contexts/VaultContext`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/add-birthday${`?${string}` | `#${string}` | ''}` | `/add-journal${`?${string}` | `#${string}` | ''}` | `/add-task${`?${string}` | `#${string}` | ''}` | `/avatar${`?${string}` | `#${string}` | ''}` | `/birthday-detail${`?${string}` | `#${string}` | ''}` | `/chat-history${`?${string}` | `#${string}` | ''}` | `/chat${`?${string}` | `#${string}` | ''}` | `/docs${`?${string}` | `#${string}` | ''}` | `/emotion${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/journal${`?${string}` | `#${string}` | ''}` | `/tasks${`?${string}` | `#${string}` | ''}` | `/vault${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/contexts/VaultContext${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/add-birthday`; params?: Router.UnknownInputParams; } | { pathname: `/add-journal`; params?: Router.UnknownInputParams; } | { pathname: `/add-task`; params?: Router.UnknownInputParams; } | { pathname: `/avatar`; params?: Router.UnknownInputParams; } | { pathname: `/birthday-detail`; params?: Router.UnknownInputParams; } | { pathname: `/chat-history`; params?: Router.UnknownInputParams; } | { pathname: `/chat`; params?: Router.UnknownInputParams; } | { pathname: `/docs`; params?: Router.UnknownInputParams; } | { pathname: `/emotion`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/journal`; params?: Router.UnknownInputParams; } | { pathname: `/tasks`; params?: Router.UnknownInputParams; } | { pathname: `/vault`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/contexts/VaultContext`; params?: Router.UnknownInputParams; };
    }
  }
}
